# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mvcwebapp:
    image: mvcwebapp
    build:
      context: .
      dockerfile: mvc-web-app/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTION=Server=sqldb;Database=Blogging;User=sa;Password=Password123;
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  webapi:
    image: mywebapi
    build:
      context: .
      dockerfile: mywebapi/Dockerfile
    ports:
      - 8081:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTION=Server=sqldb;Database=Blogging;User=sa;Password=Password123;
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: example_123
      MSSQL_PID: developer
    expose: 
      - 1499:1433
    image: mcr.microsoft.com/mssql/server:2019-latest
