apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mvcwebapp
  name: mvcwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mvcwebapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mvcwebapp
    spec:
      containers: 
      - image: mvcwebapp
        imagePullPolicy: "IfNotPresent"
        name: mvcwebapp
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: ASPNETCORE_ENVIRONMENT 
          value: Development
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
